function CodeDefine() { 
this.def = new Array();
this.def["IsrOverrun"] = {file: "ert_main_c.html",line:8,type:"var"};
this.def["isRateRunning"] = {file: "ert_main_c.html",line:9,type:"var"};
this.def["need2runFlags"] = {file: "ert_main_c.html",line:11,type:"var"};
this.def["rt_OneStep"] = {file: "ert_main_c.html",line:13,type:"fcn"};
this.def["stopRequested"] = {file: "ert_main_c.html",line:98,type:"var"};
this.def["main"] = {file: "ert_main_c.html",line:99,type:"fcn"};
this.def["basic_B"] = {file: "basic_c.html",line:26,type:"var"};
this.def["basic_DW"] = {file: "basic_c.html",line:29,type:"var"};
this.def["basic_M_"] = {file: "basic_c.html",line:32,type:"var"};
this.def["basic_M"] = {file: "basic_c.html",line:33,type:"var"};
this.def["basic_SetEventsForThisBaseStep"] = {file: "basic_c.html",line:52,type:"fcn"};
this.def["rate_monotonic_scheduler"] = {file: "basic_c.html",line:66,type:"fcn"};
this.def["arduino_PWMOutput_arduino_PWMOu"] = {file: "basic_c.html",line:91,type:"fcn"};
this.def["SystemProp_matlabCodegenSetAnyP"] = {file: "basic_c.html",line:119,type:"fcn"};
this.def["matlabCodegenHandle_matlabCodeg"] = {file: "basic_c.html",line:128,type:"fcn"};
this.def["SystemProp_matlabCodegenSetA_b0"] = {file: "basic_c.html",line:140,type:"fcn"};
this.def["matlabCodegenHandle_matlabCo_b0"] = {file: "basic_c.html",line:147,type:"fcn"};
this.def["basic_step0"] = {file: "basic_c.html",line:158,type:"fcn"};
this.def["basic_step2"] = {file: "basic_c.html",line:245,type:"fcn"};
this.def["basic_initialize"] = {file: "basic_c.html",line:394,type:"fcn"};
this.def["basic_terminate"] = {file: "basic_c.html",line:571,type:"fcn"};
this.def["B_basic_T"] = {file: "basic_h.html",line:106,type:"type"};
this.def["DW_basic_T"] = {file: "basic_h.html",line:148,type:"type"};
this.def["cell_basic_T"] = {file: "basic_types_h.html",line:44,type:"type"};
this.def["codertarget_arduinobase_inter_T"] = {file: "basic_types_h.html",line:53,type:"type"};
this.def["codertarget_arduinobase_int_b_T"] = {file: "basic_types_h.html",line:67,type:"type"};
this.def["codertarget_arduinobase_in_b0_T"] = {file: "basic_types_h.html",line:80,type:"type"};
this.def["P_basic_T"] = {file: "basic_types_h.html",line:85,type:"type"};
this.def["RT_MODEL_basic_T"] = {file: "basic_types_h.html",line:88,type:"type"};
this.def["basic_P"] = {file: "basic_data_c.html",line:25,type:"var"};
this.def["chunk_T"] = {file: "multiword_types_h.html",line:28,type:"type"};
this.def["uchunk_T"] = {file: "multiword_types_h.html",line:29,type:"type"};
this.def["long_T"] = {file: "multiword_types_h.html",line:34,type:"type"};
this.def["int64m_T"] = {file: "multiword_types_h.html",line:41,type:"type"};
this.def["cint64m_T"] = {file: "multiword_types_h.html",line:46,type:"type"};
this.def["uint64m_T"] = {file: "multiword_types_h.html",line:50,type:"type"};
this.def["cuint64m_T"] = {file: "multiword_types_h.html",line:55,type:"type"};
this.def["int96m_T"] = {file: "multiword_types_h.html",line:59,type:"type"};
this.def["cint96m_T"] = {file: "multiword_types_h.html",line:64,type:"type"};
this.def["uint96m_T"] = {file: "multiword_types_h.html",line:68,type:"type"};
this.def["cuint96m_T"] = {file: "multiword_types_h.html",line:73,type:"type"};
this.def["int128m_T"] = {file: "multiword_types_h.html",line:77,type:"type"};
this.def["cint128m_T"] = {file: "multiword_types_h.html",line:82,type:"type"};
this.def["uint128m_T"] = {file: "multiword_types_h.html",line:86,type:"type"};
this.def["cuint128m_T"] = {file: "multiword_types_h.html",line:91,type:"type"};
this.def["int160m_T"] = {file: "multiword_types_h.html",line:95,type:"type"};
this.def["cint160m_T"] = {file: "multiword_types_h.html",line:100,type:"type"};
this.def["uint160m_T"] = {file: "multiword_types_h.html",line:104,type:"type"};
this.def["cuint160m_T"] = {file: "multiword_types_h.html",line:109,type:"type"};
this.def["int192m_T"] = {file: "multiword_types_h.html",line:113,type:"type"};
this.def["cint192m_T"] = {file: "multiword_types_h.html",line:118,type:"type"};
this.def["uint192m_T"] = {file: "multiword_types_h.html",line:122,type:"type"};
this.def["cuint192m_T"] = {file: "multiword_types_h.html",line:127,type:"type"};
this.def["int224m_T"] = {file: "multiword_types_h.html",line:131,type:"type"};
this.def["cint224m_T"] = {file: "multiword_types_h.html",line:136,type:"type"};
this.def["uint224m_T"] = {file: "multiword_types_h.html",line:140,type:"type"};
this.def["cuint224m_T"] = {file: "multiword_types_h.html",line:145,type:"type"};
this.def["int256m_T"] = {file: "multiword_types_h.html",line:149,type:"type"};
this.def["cint256m_T"] = {file: "multiword_types_h.html",line:154,type:"type"};
this.def["uint256m_T"] = {file: "multiword_types_h.html",line:158,type:"type"};
this.def["cuint256m_T"] = {file: "multiword_types_h.html",line:163,type:"type"};
this.def["pointer_T"] = {file: "rtwtypes_h.html",line:28,type:"type"};
this.def["rtDataTypeSizes"] = {file: "basic_dt_h.html",line:24,type:"var"};
this.def["rtDataTypeNames"] = {file: "basic_dt_h.html",line:44,type:"var"};
this.def["rtBTransitions"] = {file: "basic_dt_h.html",line:64,type:"var"};
this.def["rtBTransTable"] = {file: "basic_dt_h.html",line:84,type:"var"};
this.def["rtPTransitions"] = {file: "basic_dt_h.html",line:90,type:"var"};
this.def["rtPTransTable"] = {file: "basic_dt_h.html",line:101,type:"var"};
this.def["MW_AnalogInSingle_Open"] = {file: "MW_AnalogInput_cpp.html",line:14,type:"fcn"};
this.def["MW_AnalogIn_SetTriggerSource"] = {file: "MW_AnalogInput_cpp.html",line:31,type:"fcn"};
this.def["MW_AnalogIn_EnableNotification"] = {file: "MW_AnalogInput_cpp.html",line:39,type:"fcn"};
this.def["MW_AnalogIn_DisableNotification"] = {file: "MW_AnalogInput_cpp.html",line:45,type:"fcn"};
this.def["MW_AnalogIn_EnableContConversion"] = {file: "MW_AnalogInput_cpp.html",line:51,type:"fcn"};
this.def["MW_AnalogIn_SetChannelConvRank"] = {file: "MW_AnalogInput_cpp.html",line:57,type:"fcn"};
this.def["MW_AnalogIn_GetStatus"] = {file: "MW_AnalogInput_cpp.html",line:65,type:"fcn"};
this.def["MW_AnalogInSingle_ReadResult"] = {file: "MW_AnalogInput_cpp.html",line:71,type:"fcn"};
this.def["MW_AnalogIn_Start"] = {file: "MW_AnalogInput_cpp.html",line:85,type:"fcn"};
this.def["MW_AnalogIn_Stop"] = {file: "MW_AnalogInput_cpp.html",line:91,type:"fcn"};
this.def["MW_AnalogIn_Close"] = {file: "MW_AnalogInput_cpp.html",line:97,type:"fcn"};
this.def["MW_AnalogIn_GetHandle"] = {file: "MW_AnalogInput_cpp.html",line:102,type:"fcn"};
this.def["MW_PWM_Open"] = {file: "MW_PWM_cpp.html",line:14,type:"fcn"};
this.def["MW_PWM_Start"] = {file: "MW_PWM_cpp.html",line:26,type:"fcn"};
this.def["MW_PWM_SetDutyCycle"] = {file: "MW_PWM_cpp.html",line:32,type:"fcn"};
this.def["MW_PWM_SetFrequency"] = {file: "MW_PWM_cpp.html",line:47,type:"fcn"};
this.def["MW_PWM_DisableNotification"] = {file: "MW_PWM_cpp.html",line:54,type:"fcn"};
this.def["MW_PWM_EnableNotification"] = {file: "MW_PWM_cpp.html",line:60,type:"fcn"};
this.def["MW_PWM_SetOutputToIdle"] = {file: "MW_PWM_cpp.html",line:67,type:"fcn"};
this.def["MW_PWM_GetOutputState"] = {file: "MW_PWM_cpp.html",line:73,type:"fcn"};
this.def["MW_PWM_Stop"] = {file: "MW_PWM_cpp.html",line:80,type:"fcn"};
this.def["MW_PWM_Close"] = {file: "MW_PWM_cpp.html",line:86,type:"fcn"};
this.def["getLoopbackIP"] = {file: "MW_target_hardware_resources_h.html",line:12,type:"var"};
}
CodeDefine.instance = new CodeDefine();
var testHarnessInfo = {OwnerFileName: "", HarnessOwner: "", HarnessName: "", IsTestHarness: "0"};
var relPathToBuildDir = "../ert_main.c";
var fileSep = "/";
var isPC = false;
function Html2SrcLink() {
	this.html2SrcPath = new Array;
	this.html2Root = new Array;
	this.html2SrcPath["ert_main_c.html"] = "../ert_main.c";
	this.html2Root["ert_main_c.html"] = "ert_main_c.html";
	this.html2SrcPath["basic_c.html"] = "../basic.c";
	this.html2Root["basic_c.html"] = "basic_c.html";
	this.html2SrcPath["basic_h.html"] = "../basic.h";
	this.html2Root["basic_h.html"] = "basic_h.html";
	this.html2SrcPath["basic_private_h.html"] = "../basic_private.h";
	this.html2Root["basic_private_h.html"] = "basic_private_h.html";
	this.html2SrcPath["basic_types_h.html"] = "../basic_types.h";
	this.html2Root["basic_types_h.html"] = "basic_types_h.html";
	this.html2SrcPath["basic_data_c.html"] = "../basic_data.c";
	this.html2Root["basic_data_c.html"] = "basic_data_c.html";
	this.html2SrcPath["multiword_types_h.html"] = "../multiword_types.h";
	this.html2Root["multiword_types_h.html"] = "multiword_types_h.html";
	this.html2SrcPath["rtwtypes_h.html"] = "../rtwtypes.h";
	this.html2Root["rtwtypes_h.html"] = "rtwtypes_h.html";
	this.html2SrcPath["basic_dt_h.html"] = "../basic_dt.h";
	this.html2Root["basic_dt_h.html"] = "basic_dt_h.html";
	this.html2SrcPath["rtmodel_h.html"] = "../rtmodel.h";
	this.html2Root["rtmodel_h.html"] = "rtmodel_h.html";
	this.html2SrcPath["MW_AnalogInput_cpp.html"] = "../../../../../MATLAB/SupportPackages/R2018a/toolbox/target/supportpackages/arduinobase/src/MW_AnalogInput.cpp";
	this.html2Root["MW_AnalogInput_cpp.html"] = "MW_AnalogInput_cpp.html";
	this.html2SrcPath["MW_PWM_cpp.html"] = "../../../../../MATLAB/SupportPackages/R2018a/toolbox/target/supportpackages/arduinobase/src/MW_PWM.cpp";
	this.html2Root["MW_PWM_cpp.html"] = "MW_PWM_cpp.html";
	this.html2SrcPath["MW_target_hardware_resources_h.html"] = "../MW_target_hardware_resources.h";
	this.html2Root["MW_target_hardware_resources_h.html"] = "MW_target_hardware_resources_h.html";
	this.getLink2Src = function (htmlFileName) {
		 if (this.html2SrcPath[htmlFileName])
			 return this.html2SrcPath[htmlFileName];
		 else
			 return null;
	}
	this.getLinkFromRoot = function (htmlFileName) {
		 if (this.html2Root[htmlFileName])
			 return this.html2Root[htmlFileName];
		 else
			 return null;
	}
}
Html2SrcLink.instance = new Html2SrcLink();
var fileList = [
"ert_main_c.html","basic_c.html","basic_h.html","basic_private_h.html","basic_types_h.html","basic_data_c.html","multiword_types_h.html","rtwtypes_h.html","basic_dt_h.html","rtmodel_h.html","MW_AnalogInput_cpp.html","MW_PWM_cpp.html","MW_target_hardware_resources_h.html"];
